#############################################################################
# iFAQMaker                                (c) 2004-2008 by Itzchak Rehberg #
# written by Itzchak Rehberg <izzysoft AT qumran DOT org>                   #
# http://www.izzysoft.de/                                                   #
# ------------------------------------------------------------------------- #
# This program is free software; you can redistribute and/or modify it      
# under the terms of the GNU General Public License (see doc/LICENSE)       #
# ------------------------------------------------------------------------- #
# Sample "TransTable" file (translations - also file names to description   #
# mappings, since it is used on the topic as well)                          #
#############################################################################

docu;Documentation
toc;TableofContents
ppvp;<span class='progname'>phpVideoPro</span>
pvp;phpVideoPro
pfaqmaker;<span class='progname'>iFAQMaker</span>
faqmaker;iFAQMaker
demofiles;DemoFiles
