<?php
 #############################################################################
 # FAQMaker                                      (c) 2004 by Itzchak Rehberg #
 # written by Itzchak Rehberg <izzysoft@qumran.org>                          #
 # http://www.qumran.org/homes/izzy/                                         #
 # ------------------------------------------------------------------------- #
 # This program is free software; you can redistribute and/or modify it      
 # under the terms of the GNU General Public License (see doc/LICENSE)       #
 # ------------------------------------------------------------------------- #
 # Sample "TransTable" file (file names to description mappings)             #
 #############################################################################

 /* $Id$ */

  $fsLang["docu"]      = "Documentation";
  $fsLang["toc"]       = "Table of Contents";
  $fsLang["ppvp"]      = "<span class='progname'>phpVideoPro</span>";
  $fsLang["pvp"]       = "phpVideoPro";
  $fsLang["pfaqmaker"] = "<span class='progname'>FAQMaker</span>";
  $fsLang["faqmaker"]  = "FAQMaker";
  $fsLang["demofiles"] = "Demo Files";
?>