<?php
 #############################################################################
 # iFAQMaker                                (c) 2004-2007 by Itzchak Rehberg #
 # written by Itzchak Rehberg <izzysoft AT qumran DOT org>                   #
 # http://www.izzysoft.de/                                                   #
 # ------------------------------------------------------------------------- #
 # This program is free software; you can redistribute and/or modify it      
 # under the terms of the GNU General Public License (see doc/LICENSE)       #
 # ------------------------------------------------------------------------- #
 # Sample "TransTable" file (file names to description mappings)             #
 #############################################################################

 /* $Id$ */

  $fsLang["docu"]      = "Documentation";
  $fsLang["toc"]       = "Table of Contents";
  $fsLang["ppvp"]      = "<span class='progname'>phpVideoPro</span>";
  $fsLang["pvp"]       = "phpVideoPro";
  $fsLang["pfaqmaker"] = "<span class='progname'>iFAQMaker</span>";
  $fsLang["faqmaker"]  = "iFAQMaker";
  $fsLang["demofiles"] = "Demo Files";
?>